Setup dwmc patch for dwm control

diff --git a/dwmc b/dwmc
--- a/dwmc
+++ b/dwmc
@@ -1,13 +1,14 @@
 #!/usr/bin/env sh
 
 signal() {
+  echo $*
 	xsetroot -name "fsignal:$*"
 }
 
 case $# in
 1)
 	case $1 in
-	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit)
+	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit | spawn)
 		signal $1
 		;;
 	*)
@@ -18,6 +19,9 @@ case $# in
 	;;
 2)
 	case $1 in
+  spawn)
+    signal $1 v $2
+    ;;
 	view)
 		signal $1 ui $2
 		;;
@@ -34,7 +38,14 @@ case $# in
 	esac
 	;;
 *)
-	echo "Too many arguments."
-	exit 1
+	case $1 in
+	spawn)
+		signal $1 v "${@:2}"
+		;;
+	*)
+		echo "Unknown command or missing one argument."
+		exit 1
+		;;
+	esac
 	;;
 esac
